# Use this for gradio container
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Install UI dependencies
RUN pip install --no-cache-dir \
    gradio \
    requests \
    numpy \
    pillow \
    python-dotenv \
    opencv-python-headless

# No harm in copying all .py files for our use-case and avoids having to update the list
COPY *.py ./
COPY file/ ./file/

EXPOSE 7860

CMD ["python", "gradio_app.py"]