FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow==2.14.1 huggingface_hub
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir opencv-python-headless

RUN pip install --no-cache-dir \
    torch torchvision --index-url https://download.pytorch.org/whl/cpu \
    opencv-python-headless \
    lightning

RUN pip install --no-cache-dir \
    mlflow==2.14.1 \
    lightning==2.2.1 \
    huggingface_hub \
    torchmetrics \
    opencv-python-headless \

COPY create_logger.py .
COPY MODEL_export_to_hf.py .
COPY models_custom_module.py .

RUN mkdir -p /mlflow_data