FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Install a SPECIFIC version of MLflow. 
# We pin this to match the version in your training container.
RUN pip install mlflow==2.14.1 psycopg2-binary

# Expose the default MLflow port
EXPOSE 5000

# Set the entrypoint to run the server
CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:////mlflow_data/mlflow.db", \
     "--default-artifact-root", "/mlflow_data/artifacts"]